In [1]:
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn import preprocessing

Using TensorFlow backend.


In [2]:
data = pd.read_csv('C://Users/baljot/Desktop/csc177 notebooks/jupyter notebook/Admission_Predict_Ver1.1_small_data_set_for_Linear_Regression.csv', header = 'infer')


In [3]:
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)

In [4]:
# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_

# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
import collections
def to_xy(df, target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)
    # find out the type of the target column. 
    target_type = df[target].dtypes
    target_type = target_type[0] if isinstance(target_type, collections.Sequence) else target_type
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32):
        # Classification
        dummies = pd.get_dummies(df[target])
        return df[result].values.astype(np.float32), dummies.values.astype(np.float32)
    else:
        # Regression
        return df[result].values.astype(np.float32), df[target].values.astype(np.float32)

In [5]:
data = data.drop('Serial No.', axis = 1)
data.head(10)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   
5        330          115                  5  4.5   3.0  9.34         1   
6        321          109                  3  3.0   4.0  8.20         1   
7        308          101                  2  3.0   4.0  7.90         0   
8        302          102                  1  2.0   1.5  8.00         0   
9        323          108                  3  3.5   3.0  8.60         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65  
5              0.90  
6              0.75  
7              0.68  
8              0.50  
9              0.45

In [6]:
admissionChance = []
targetVal = 0.70
for row in data['Chance of Admit ']:
    if row >= 0.70:
        admissionChance.append(1.0)
    elif row < 0.70:
        admissionChance.append(0.0)
data['Chance of Admit '] = admissionChance
Admissions = encode_text_index(data,'Chance of Admit ')
data.head(11)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0         337          118                  4  4.5   4.5  9.65         1   
1         324          107                  4  4.0   4.5  8.87         1   
2         316          104                  3  3.0   3.5  8.00         1   
3         322          110                  3  3.5   2.5  8.67         1   
4         314          103                  2  2.0   3.0  8.21         0   
5         330          115                  5  4.5   3.0  9.34         1   
6         321          109                  3  3.0   4.0  8.20         1   
7         308          101                  2  3.0   4.0  7.90         0   
8         302          102                  1  2.0   1.5  8.00         0   
9         323          108                  3  3.5   3.0  8.60         0   
10        325          106                  3  3.5   4.0  8.40         1   

    Chance of Admit   
0                  1  
1                  1  
2                  1  
3                  1  
4                  0  
5                  1  
6                  1  
7                  0  
8                  0  
9                  0  
10                 0

In [7]:
testData = []
for i,row in data.iterrows() :
    if(i<151):
        testData.append(row)
testData = pd.DataFrame(testData)
testData.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0      337.0        118.0                4.0  4.5   4.5  9.65       1.0   
1      324.0        107.0                4.0  4.0   4.5  8.87       1.0   
2      316.0        104.0                3.0  3.0   3.5  8.00       1.0   
3      322.0        110.0                3.0  3.5   2.5  8.67       1.0   
4      314.0        103.0                2.0  2.0   3.0  8.21       0.0   

   Chance of Admit   
0               1.0  
1               1.0  
2               1.0  
3               1.0  
4               0.0

In [8]:
encode_text_index(testData,'Chance of Admit ')
Admissions

array([0., 1.])

In [9]:
X,Y = to_xy(data,'Chance of Admit ')
testX, testY = to_xy(testData,'Chance of Admit ')


In [10]:
print(X.shape)
print (Y.shape)
Y

(500, 7)
(500, 2)


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [11]:
model = Sequential()
model.add(Dense(12, input_dim = X.shape[1], activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam')
model.fit(X,Y,verbose=2, epochs=120)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/120
 - 1s - loss: 1.1070
Epoch 2/120
 - 0s - loss: 0.8860
Epoch 3/120
 - 0s - loss: 0.8924
Epoch 4/120
 - 0s - loss: 0.8707
Epoch 5/120
 - 0s - loss: 0.8571
Epoch 6/120
 - 0s - loss: 0.8131
Epoch 7/120
 - 0s - loss: 0.8036
Epoch 8/120
 - 0s - loss: 0.7828
Epoch 9/120
 - 0s - loss: 0.7716
Epoch 10/120
 - 0s - loss: 0.7725
Epoch 11/120
 - 0s - loss: 0.7385
Epoch 12/120
 - 0s - loss: 0.7560
Epoch 13/120
 - 0s - loss: 0.7679
Epoch 14/120
 - 0s - loss: 0.7031
Epoch 15/120
 - 0s - loss: 0.6910
Epoch 16/120
 - 0s - loss: 0.6749
Epoch 17/120
 - 0s - loss: 0.6664
Epoch 18/120
 - 0s - loss: 0.6554
Epoch 19/120
 - 0s - loss: 0.6732
Epoch 20/120
 - 0s - loss: 0.6669
Epoch 21/120
 - 0s - loss: 0.6419
Epoch 22/120
 - 0s - loss: 0.6359
Epoch 23/120
 - 0s - loss: 0.6261
Epoch 24/120
 - 0s - loss: 0.6082
Epoch 25/120
 - 0s - loss: 0.6047
Epoch 26/120
 - 0s - loss: 0.5949
Epoch

In [12]:
pred = model.predict(testX)
print (pred[0])

[0.07015309 0.9298469 ]


In [13]:
pred = np.argmax(pred,axis = 1)

In [14]:
true = np.argmax(testY,axis = 1)

In [15]:
Admissions[pred]

array([1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.])

In [16]:
Admissions[true]

array([1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score,recall_score,classification_report
print('Accuracy on test data is %.2f' % (accuracy_score(true, pred)))

Accuracy on test data is 0.77


In [18]:
print(classification_report(true,pred))

              precision    recall  f1-score   support

           0       0.89      0.58      0.70        69
           1       0.73      0.94      0.82        82

   micro avg       0.77      0.77      0.77       151
   macro avg       0.81      0.76      0.76       151
weighted avg       0.80      0.77      0.77       151

